stages:
  - build
  # - upload
  # - release

build:
  stage: build
  image: node:18-bookworm
  only:
    - tags
  script:
    - npm i -g @neutralinojs/neu
    - yarn
    - yarn release
  artifacts:
    name: '$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME-$CI_JOB_NAME'
    paths:
      - dist/
# upload:
#   stage: upload
#   image: curlimages/curl:latest
#   only:
#     - tags
#   script:
#     - 'curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file dist/quack-${CI_COMMIT_TAG} ${PACKAGE_REGISTRY_URL}/-${CI_COMMIT_TAG}'
